name: CI/CD Pipeline for FastAPI Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    # Install Render CLI
    - name: Install Render CLI
      run: |
        curl -fsSL https://cli.render.com/install | bash
        export PATH=$PATH:/root/.local/bin
        render --version  # Verify installation

    # Deploy to Render
    - name: Deploy to Render
      run: |
        export PATH=$PATH:/root/.local/bin  # Ensure PATH includes Render CLI
        render services update api --api-key rnd_fJ4PumLUh0CL5KUby29Vi0Wp7nhJ --envfile .env
