name: Deploy Titanic API to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Explicitly install pytest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Render CLI
    - name: Install Render CLI
      run: |
        curl -fsSL https://cli.render.com/install | bash
        export PATH=$PATH:/root/.local/bin  # Add Render CLI to PATH
        render --version  # Verify installation

    # Step 3: Deploy to Render
    - name: Deploy to Render
      run: |
        export PATH=$PATH:/root/.local/bin  # Ensure PATH includes Render CLI
        render services update api --api-key rnd_fJ4PumLUh0CL5KUby29Vi0Wp7nhJ --envfile .env
